### ISSUE TITLE
Support INPUT_OBJECT?

### ISSUE THREAD

**Issue by philiptzou** [mhallin/graphql-docs#1]
Hello,

I am trying to use this module to generate document for my GraphQL API. But I received this error:

```
d49cce02-13a4-11e6-8e2e-46e2b2239122.js:1 Uncaught (in promise) Error: Unsupported type ref kind: INPUT_OBJECT
```

I use GraphQL-Java as my backend but [I guess things could also go wrong with node version](http://graphql.org/docs/api-reference-type-system/#graphqlinputobjecttype).

**Comment by mhallin** [comment]
Great feedback!

I've implemented rudimentary support in release 0.1.4.
